=== colorer/Colorer-library-svn/doc/2003/catalog.dtd
<!--   DTD description of colorer-take5 CATALOG format  -->

<!ELEMENT catalog (hrc-sets, hrd-sets)>

<!ELEMENT hrc-sets (location+)>
<!ATTLIST hrc-sets
  log-location CDATA #IMPLIED>

<!ELEMENT hrd-sets (hrd*)>

<!ELEMENT hrd (location+)>
<!ATTLIST hrd
  name        NMTOKEN #REQUIRED
  class       NMTOKEN #REQUIRED
  description CDATA   #IMPLIED>

<!ELEMENT location EMPTY>
<!ATTLIST location
  link            CDATA #REQUIRED>

=== colorer/Colorer-library-svn/src/pcolorer/catalog.xml
<?xml version="1.0" encoding='UTF-8'?>
<!DOCTYPE catalog PUBLIC "-//Cail Lomecb//DTD Colorer CATALOG take5//EN"
  "http://colorer.sf.net/2003/catalog.dtd">

<catalog xmlns="http://colorer.sf.net/2003/catalog"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://colorer.sf.net/2003/catalog
                             http://colorer.sf.net/2003/catalog.xsd">

  <hrc-sets>
    <location link="hrc/colorer.hrc"/>
    <location link="hrc/auto"/>
  </hrc-sets>


  <hrd-sets>
    <hrd class="console" name="default" description="Aqua on blue">
      <location link="hrd/console/default.hrd"/>
    </hrd>
    <hrd class="console" name="blue" description="Blue colors">
      <location link="hrd/console/blue.hrd"/>
    </hrd>
    <hrd class="console" name="nc"  description="NC colors">
      <location link="hrd/console/nc.hrd"/>
    </hrd>
    <hrd class="console" name="white" description="White colors">
      <location link="hrd/console/white.hrd"/>
    </hrd>
    <hrd class="console" name="black"   description="Black colors">
      <location link="hrd/console/black.hrd"/>
    </hrd>
    <hrd class="console" name="hack"  description="Matrix/Hack">
      <location link="hrd/console/hack.hrd"/>
    </hrd>
    <hrd class="console" name="dnlike"  description="Gray a'la DN">
      <location link="hrd/console/dnlike.hrd"/>
    </hrd>
    <hrd class="console" name="gray"   description="Light gray">
      <location link="hrd/console/white.hrd"/>
      <location link="hrd/console/gray.hrd"/>
    </hrd>
    <hrd class="console" name="xmastree" description="Xmas tree">
      <location link="hrd/console/xmastree.hrd"/>
    </hrd>
    <hrd class="console" name="black_ay" description="Black from Alex Yaroslavsky">
      <location link="hrd/console/contrib/black_ay.hrd"/>
    </hrd>

  </hrd-sets>

</catalog>

=== colorer/Colorer-library-svn/colorer/catalog.xml
<?xml version="1.0" encoding='UTF-8'?>
<!DOCTYPE catalog PUBLIC "-//Cail Lomecb//DTD Colorer CATALOG take5//EN"
  "http://colorer.sf.net/2003/catalog.dtd">

<catalog xmlns="http://colorer.sf.net/2003/catalog"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://colorer.sf.net/2003/catalog
                             http://colorer.sf.net/2003/catalog.xsd">

  <hrc-sets log-location="colorer.log">
    <location link="hrc/colorer.hrc"/>
    <location link="hrc/auto"/>
<!--
    <location link="hrc/colorer.hrc"/>
    <location link="jar:hrc/common.jar!colorer.hrc"/>
    <location link="jar:http://colorer.sf.net/hrc/common.jar!colorer.hrc"/>
    <location link="http://colorer.sf.net/hrc/colorer.hrc"/>
    <location link="\\server\common\colorer\hrc\colorer.hrc"/>
-->
  </hrc-sets>


  <hrd-sets>
    <hrd class="console" name="default" description="Aqua on blue">
      <location link="hrd/console/default.hrd"/>
    </hrd>
    <hrd class="console" name="blue" description="Blue colors">
      <location link="hrd/console/blue.hrd"/>
    </hrd>
    <hrd class="console" name="nc"  description="NC colors">
      <location link="hrd/console/nc.hrd"/>
    </hrd>
    <hrd class="console" name="white" description="White colors">
      <location link="hrd/console/white.hrd"/>
    </hrd>
    <hrd class="console" name="black"   description="Black colors">
      <location link="hrd/console/black.hrd"/>
    </hrd>
    <hrd class="console" name="hack"  description="Matrix/Hack">
      <location link="hrd/console/hack.hrd"/>
    </hrd>
    <hrd class="console" name="dnlike"  description="Gray a'la DN">
      <location link="hrd/console/dnlike.hrd"/>
    </hrd>
    <hrd class="console" name="gray"   description="Light gray">
      <location link="hrd/console/white.hrd"/>
      <location link="hrd/console/gray.hrd"/>
    </hrd>
    <hrd class="console" name="xmastree" description="Xmas tree">
      <location link="hrd/console/xmastree.hrd"/>
    </hrd>
    <hrd class="console" name="ocean" description="Ocean Vladimir Fonarev">
      <location link="hrd/console/contrib/ocean.hrd"/>
    </hrd>
    <hrd class="console" name="black_ay" description="Black from Alex Yaroslavsky">
      <location link="hrd/console/contrib/black_ay.hrd"/>
    </hrd>
    <hrd class="console" name="mirror" description="Mirror from Eugene Efromov">
      <location link="hrd/console/contrib/mirror.hrd"/>
    </hrd>


    <hrd class="rgb" name="default" description="White (crimsoned)">
      <location link="hrd/rgb/white.hrd"/>
    </hrd>
    <hrd class="rgb" name="navy" description="Navy (seashore)">
      <location link="hrd/rgb/navy.hrd"/>
    </hrd>
    <hrd class="rgb" name="eclipse" description="A'la Eclipse (minimal)">
      <location link="hrd/rgb/eclipse.hrd"/>
    </hrd>
    <hrd class="rgb" name="neo" description="Neo (and Morpheus)">
      <location link="hrd/rgb/neo.hrd"/>
    </hrd>
    <hrd class="rgb" name="black"  description="Black (scarlet)">
      <location link="hrd/rgb/black.hrd"/>
    </hrd>
    <hrd class="rgb" name="grayscale" description="Grayscale (colour neutral)">
      <location link="hrd/rgb/grayscale.hrd"/>
    </hrd>
    <hrd class="rgb" name="fmx" description="FMX">
      <location link="hrd/rgb/contrib/fmx.hrd"/>
    </hrd>


    <hrd class="text" name="tags" description="HTML italic, underline indention">
      <location link="hrd/text/tags.hrd"/>
    </hrd>

  </hrd-sets>

</catalog>

=== colorer/Colorer-library-svn/colorer/src/net.sf.colorer/distr/catalog.xml
<?xml version="1.0" encoding='UTF-8'?>
<!DOCTYPE catalog PUBLIC "-//Cail Lomecb//DTD Colorer CATALOG take5//EN"
  "http://colorer.sf.net/2003/catalog.dtd">

<catalog xmlns="http://colorer.sf.net/2003/catalog"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://colorer.sf.net/2003/catalog
                             http://colorer.sf.net/2003/catalog.xsd">

  <hrc-sets>
    <location link="hrc/proto.hrc"/>
    <location link="hrc/auto/ccsql.hrc"/>
    <location link="hrc/auto/farmanager.hrc"/>
    <location link="hrc/auto/gen.hrc"/>
    <location link="hrc/auto/litestep.hrc"/>
    <location link="hrc/auto/qrm.hrc"/>
    <location link="hrc/auto/rare-scripts.hrc"/>
    <location link="hrc/auto/vim.hrc"/>
  </hrc-sets>

  <hrd-sets>
    <hrd class="rgb" name="default" description="White (crimsoned)">
      <location link="hrd/rgb/white.hrd"/>
    </hrd>
    <hrd class="rgb" name="navy" description="Navy (seashore)">
      <location link="hrd/rgb/navy.hrd"/>
    </hrd>
    <hrd class="rgb" name="eclipse" description="A'la Eclipse (minimal)">
      <location link="hrd/rgb/eclipse.hrd"/>
    </hrd>
    <hrd class="rgb" name="neo" description="Neo (and Morpheus)">
      <location link="hrd/rgb/neo.hrd"/>
    </hrd>
    <hrd class="rgb" name="black"  description="Black (scarlet)">
      <location link="hrd/rgb/black.hrd"/>
    </hrd>
    <hrd class="rgb" name="grayscale" description="Grayscale (colour neutral)">
      <location link="hrd/rgb/grayscale.hrd"/>
    </hrd>
    <hrd class="rgb" name="fmx" description="FMX">
      <location link="hrd/rgb/contrib/fmx.hrd"/>
    </hrd>
    <hrd class="rgb" name="hs" description="A'la HomeSite">
      <location link="hrd/rgb/hs.hrd"/>
    </hrd>
    <hrd class="rgb" name="bred3" description="Bred3 colors">
      <location link="hrd/rgb/contrib/bred3.hrd"/>
    </hrd>
  </hrd-sets>

</catalog>
